<?php
/**
 * 描述.
 *
 * @author duanjin<duan.jin@mydreamplus.com>
 * @date 2016-12-30 14:35
 */

namespace Tests;
use App\Repositories;

class TestRepository extends \TestCase
{
    protected $userRep;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userRep = new Repositories\UserRepository();
    }

    public function testAddUser()
    {
        $data = array(
            'name' => 'test111',
            'role' => 1,
            'avatar' => 'this is test',
            'email' => '240333175@qq.com',
            'password' =>'testtesttest',
            'more' => 'test',
            'root_day' => 5,
        );
        $res = $this->userRep->insertUser($data);dd($res);
    }
}